AppBundle\Entity\Member:
    type: entity
      # ...
    manyToOne:
        category:
            targetEntity: AppBundle\Entity\Category
            inversedBy: members
            joinColumn:
                nullable: true