# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    role_hierarchy:
      ROLE_ADMIN: [ROLE_USER]

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
        AppBundle\Entity\Member:
            algorithm: bcrypt

    providers:
      chain_provider:
        chain:
          providers:
            - in_memory
            - db_provider
      in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$sBG1nMvGxgY.AprC/tYl5ecuDvxT66bYNRrdX0zAyQCqQiUX./fqS
                        roles: 'ROLE_ADMIN'

      db_provider:
        entity:
          class: AppBundle:Member
          property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider: chain_provider
            form_login:
                login_path: login
                failure_path: login
                check_path: login
                success_handler: crv.authentication.success_handlers
                success_handler: crv.authentication.failure_handlers
            logout: true

            anonymous: ~

            remember_me:
              secret: '%secret%'
              lifetime: 604800
              path: /
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~


    access_control:
      - {path: ^/(login|register)$, role: IS_AUTHENTICATED_ANONYMOUSLY}
      - {path: ^/registration-form-submission$, role: IS_AUTHENTICATED_ANONYMOUSLY}
      - {path: ^/recover$, role: IS_AUTHENTICATED_ANONYMOUSLY}
      - {path: ^/reset/confirm$, role: IS_AUTHENTICATED_ANONYMOUSLY}
      - {path: ^/reset/request$, role: IS_AUTHENTICATED_ANONYMOUSLY}
      - {path: ^/, role: ROLE_USER}
      - {path: ^/illness$, role: ROLE_USER}